### DISCUSSION TITLE
mirroring sample removed?  is there anything wrong in mirroring sample?

### DISCUSSION THREAD

**Discussion by motocoder-cn** [iter8-tools/iter8#1061] [Q&A] [answered]
i read docs in :https://iter8.tools/0.6/tutorials/traffic-engineering/mirroring/

but i do not understand how follow virtualservice can mirror request ?

this virtualservice request & mirror  request with:
 **same host: knative-local-gateway.istio-system.svc.cluster.local
 same authority: example.com**

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-mirroring
spec:
  gateways:
  - mesh
  - knative-serving/knative-ingress-gateway
  hosts:
  - example.com
  http:
  - rewrite:
      authority: example.com
    route:
    - destination:
        host: knative-local-gateway.istio-system.svc.cluster.local
    mirror:
      host: knative-local-gateway.istio-system.svc.cluster.local
    mirrorPercent: 40
```
**prefix: example.com-shadow will never match**
can sample-app-v2.default.svc.cluster.local be called?

i found mirroring sample has been removed, is this wrong?

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-routing
spec:
  gateways:
  - knative-serving/knative-local-gateway
  hosts:
  - "*"
  http:
  - match:
    - authority:
        prefix: example.com-shadow
    route:
    - destination:
        host: sample-app-v2.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: sample-app-v2
  - match:
    - authority:
        prefix: example.com
    route:
    - destination:
        host: sample-app-v1.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: sample-app-v1
```
