### DISCUSSION TITLE
Ideas for notification tasks

### DISCUSSION THREAD

**Discussion by sriumcp** [iter8-tools/iter8#676] [Ideas]
```yaml
- task: notification/slack
  with:
     channel: <string>
     secret: <namespace/name> -- reference to a K8s secret
```

```yaml
- task: notification/email
  with: 
    url: smtps://smtp.gmail.com:465
    secret: <namespace/name> -- reference to a basic auth K8s secret
    mail-from: username@gmail.com
    mail-rcpt: john@example.com
```

```yaml
- task: notification/webhook
  with:
    url: https://my.webhook.service
    secret: <namespace/name> -- reference to a basic auth K8s secret
    authType: <one of the Iter8 supported authentication types>
```

**Comment by sriumcp** [comment]
```yaml
duration:
  maxLoops: 20
  numIterationsPerLoop: 10
  interval: 50 # seconds
```

```yaml
loop:
- task: notification/slack
  with:
  ... see above
- task: notification/email
  with:
  ... see above
```
