### DISCUSSION TITLE
CRD changes for GitOps support

### DISCUSSION THREAD

**Discussion by sriumcp** [iter8-tools/iter8#695] [Ideas]
Sample GitOps-enabled experiment.

Before `start` action is invoked.

```yaml
apiVersion: iter8.tools/v2alpha1
kind: Experiment
metadata:
  name: experiment-1
spec:
  target: knative-test/sample-application
  strategy:
    testingPattern: Canary
    deploymentPattern: fixed-split
    actions:
      start:
      - library: knative
        task: updateExperimentInGit
        with:
          targetRepo: https://github.com/my/repo
          targetFile: path/to/folder/experiment.yaml
      loop:
      - library: knative
        task: updateKsvcInGit
        with:
          targetRepo: https://github.com/my/repo
          targetFile: path/to/folder/ksvc.yaml
      finish:
      - library: common
        task: replaceGitFolder
        with: 
          sourceFolder: https://github.com/my/repo/source/{{ .name }}
          targetRepo: https://github.com/my/repo
          targetFolder: path/to/app
  criteria:
    objectives:
    - metric: mean-latency
      upperLimit: 2000
    - metric: error-rate
      upperLimit: "0.01"
  duration:
    intervalSeconds: 3600
    maxIterations: 24
    maxLoops: 14
```

After `start` action is invoked and GitOps operator has finished syncing.

```yaml
apiVersion: iter8.tools/v2alpha1
kind: Experiment
metadata:
  name: experiment-1
spec:
  target: knative-test/sample-application
  strategy:
    testingPattern: Canary
    deploymentPattern: fixed-split
    actions:
      start:
      - library: knative
        task: updateExperimentInGit
        with:
          targetRepo: https://github.com/my/repo
          targetFile: path/to/folder/experiment.yaml
      loop:
      - library: knative
        task: updateKsvcInGit
        with:
          targetRepo: https://github.com/my/repo
          targetFile: path/to/folder/ksvc.yaml
      finish:
      - library: common
        task: replaceGitFolder
        with: 
          sourceFolder: https://github.com/my/repo/source/{{ .name }}
          targetRepo: https://github.com/my/repo
          targetFolder: path/to/app
  criteria:
    objectives:
    - metric: mean-latency
      upperLimit: 2000
    - metric: error-rate
      upperLimit: "0.01"
  duration:
    intervalSeconds: 3600
    maxIterations: 24
    maxLoops: 14
  versionInfo:
    baseline:
      name: current # names of versions MUST be unique
      variables:
      - name: revision
        value: sample-application-v1
      weightObjRef:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: sample-application
          namespace: knative-test
          fieldPath: /spec/traffic/0/percent
    candidates:
      - name: candidate
        variables: 
        - name: revision
          value: sample-application-v2
        weightObjRef:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: sample-application
          namespace: knative-test
          fieldPath: /spec/traffic/1/percent
```

**Comment by sriumcp** [comment]
Sample InCluster experiment.

Before `start` action is invoked.

```yaml
apiVersion: iter8.tools/v2alpha1
kind: Experiment
metadata:
  name: experiment-1
spec:
  target: knative-test/sample-application
  strategy:
    testingPattern: Canary
    deploymentPattern: progressive
    actions:
      start:
      - library: knative
        task: updateExperimentInCluster
      finish:
      - library: common
        task: updateInClusterResourcesUsingKubectl
        with: 
          sourceFolder: https://github.com/my/repo/{{ .name }}
  criteria:
    objectives:
    - metric: mean-latency
      upperLimit: 2000
    - metric: error-rate
      upperLimit: "0.01"
  duration:
    intervalSeconds: 3600
    maxIterations: 336
```

After `start` action is invoked.

```yaml
apiVersion: iter8.tools/v2alpha1
kind: Experiment
metadata:
  name: experiment-1
spec:
  target: knative-test/sample-application
  strategy:
    testingPattern: Canary
    deploymentPattern: progressive
    actions:
      start:
      - library: knative
        task: updateExperimentInCluster
      finish:
      - library: common
        task: updateInClusterResourcesUsingKubectl
        with: 
          sourceFolder: https://github.com/my/repo/{{ .name }}
  criteria:
    objectives:
    - metric: mean-latency
      upperLimit: 2000
    - metric: error-rate
      upperLimit: "0.01"
  duration:
    intervalSeconds: 3600
    maxIterations: 336
  versionInfo:
    baseline:
      name: current # names of versions MUST be unique
      variables:
      - name: revision
        value: sample-application-v1
      weightObjRef:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: sample-application
          namespace: knative-test
          fieldPath: /spec/traffic/0/percent
    candidates:
      - name: candidate
        variables: 
        - name: revision
          value: sample-application-v2
        weightObjRef:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: sample-application
          namespace: knative-test
          fieldPath: /spec/traffic/1/percent
```
