### DISCUSSION TITLE
New common library task to make it easier to invoke shell commands

### DISCUSSION THREAD

**Discussion by sriumcp** [iter8-tools/iter8#696] [Ideas]
```yaml
task: common/shell
# with is a JSON raw object
with: |
   curl http-end-point experiment.yaml
   git push experiment
   python script.py
```
