### DISCUSSION TITLE
New handler type: common/webhook

### DISCUSSION THREAD

**Discussion by huang195** [iter8-tools/iter8#724] [General]
Purpose:
- Webhooks are commonly supported and used for integration. Iter8 handler should support this type of integration

I want to discuss if there's a way to define a generic webhook interface, e.g., 

```yaml
task: common/webhook
with:
  URL: http://
  user: username
  secret: default/secret
  type: [GET|POST]
  body: ...
```

so that we can re-use the same interface to implement `gitops/github_action` and `notification/slack`. 

Github Action APIs are defined here: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

@kalantar @sriumcp @fabolive ^^

**Comment by sriumcp** [comment]
Nice idea... how about a twist as follows?

```yaml
actions:
- finish:
  - task: common/tekton-trigger-message # creates a slack message and populates the context with this message
    with:
      msgId: my-tekton-msg
  - task: common/github-message # creates a Tekton message and populates the context with this message
    with:
      msgId: my-gh-msg
  - task: common/webhook
    with:
      URL: http://
      user: username
      secret: default/secret
      type: [GET|POST]
      body: my-tekton-msg # creates a GH message and populates the context with this message
  - task: common/webhook
    with:
      URL: http://
      user: username
      secret: default/secret
      type: [GET|POST]
      body: my-gh-msg
```

**Reply by huang195** [reply]
AFAIK, a webhook is just a message sent to a particular URL (e.g., https://api.github.com), with a specific path (/iter8-tools/iter8/pulls), with a particular request method (e.g., GET/PUT/POST), and with or without certain parameters (e.g., ?param1=a&param2=b...), with or without payload, and with or without authentication. 

The question is do we want to implement this generic webhook interface, so it can be used as a foundation layer for upper layer services. E.g., If we were to use this generic webhook to implement a Github Action task, it would look like:

```yaml
  - task: common/webhook
    with:
      URL: https://api.github.com/iter8-tools/iter8/workflow-1/dispatches
      user: username
      secret: default/secret
      type: POST
      body: version=v2
```

but if one were to implement it in a higher-level `common/github`, it would look like
```yaml
  - task: common/github
    with:
      Action: Dispatch
      Workflow: workflow-1
      user: username
      secret: default/secret
      body: version=v2
```

The latter has a bit cleaner interface than the former. And under the cover, it would just convert `common/github` to a `common/webhook` call. I think regardless what we decide, the `common/webhook` is needed in any case. Whether or not upper layer protocols would make use of it is up to the implementer of that handler type.
