### DISCUSSION TITLE
Experiment using v2beta1 API

### DISCUSSION THREAD

**Discussion by sriumcp** [iter8-tools/iter8#942] [Ideas]
Here is an example of how an experiment might look with `v2beta1` experiment API.

```yaml
apiVersion: iter8.tools/v2beta1
kind: Experiment
metadata:
  name: hybrid-exp
spec:
  target: default/sample-app
  actions:
    loop:
    - task: load-test-with-fortio
      with:
        resolve:
          destinations: [sample-app-v1.default, sample-app-v2.default]
          timeoutSeconds: 20
        versionInfo:
        - script: fortio load -json {{ FortioOutputFile }} http://sample-app-v1.default.svc.cluster.local 
        - script: fortio load -json {{ FortioOutputFile }} http://sample-app-v2.default.svc.cluster.local 
    finish: # run the following sequence of tasks at the end of the experiment
    - run: kubectl apply -f https://raw.githubusercontent.com/iter8-tools/iter8/master/samples/knative/quickstart/candidate.yaml
      if: CandidateWon()
    - run: kubectl apply -f https://raw.githubusercontent.com/iter8-tools/iter8/master/samples/knative/quickstart/baseline.yaml
      if: not CandidateWon()
  backends:
    endpoint: # information about the endpoint
      url: https://newrelic.com
      provider: "New Relic"
    metrics:
    - name: user-engagement
      description: "users will be attracted to experiences that are simple and intuitive"
      versionInfo:
      - params: # params for version-1
      - params: # params for version-2
  criteria:
    rewards: # Business rewards
    - metric: user-engagement
      preferredDirection: High # maximize user engagement
    objectives: 
    - metric: iter8-fortio/mean-latency # iter8-fortio prefix in metrics is reserved for Iter8's internal use
      upperLimit: 50
    - metric: iter8-fortio/latency-95th-percentile
      upperLimit: 100
    - metric: iter8-fortio/error-rate
      upperLimit: "0.01"
    requestCount: iter8-system/request-count
  duration:
    maxLoops: 10
    intervalSeconds: 1
  versionNames: ["sample-app-v1", "sample-app-v2"]
```
