### DISCUSSION TITLE
Duration and metrics/collect task

### DISCUSSION THREAD

**Discussion by kalantar** [iter8-tools/iter8#965] [General]
An experiment expresses duration as: 

```yaml
...
duration:
  intervalSeconds: 5
  iterationsPerLoop: 10
  maxLoops: 15
...
```

A lower bound for execution time is then  `itervalSeconds * iterationsPerLoop * maxLoops`. However, actual running time is also related to task execution. Of these, `metrics/collect` has a big influence. Our first experiment has the duration values all set to 1 but still takes some time to complete because of the task.

Using builtin metrics, it is easy to specify duration poorly. `iterationsPerLoop` should probably always be `1`.  If the task is a `start` task, `maxLoops` should also be 1. If a `loop` task, should be something else.

Is there anything we can do to make this easier and clearer?
