### ISSUE TITLE
Expand `metrics/collect` inputs so that it can take better advantage of Fortio's load testing capabilities

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1000]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Support numQueries, payload string, and content type in `metrics/collect`.

**Describe the feature/solution you'd like**
```yaml
- task: metrics/collect
  with:
    numQueries: <number of queries to send> # default = 100 # new input
    time: <duration as it exists today> # if both numQueries and time are specified, numQueries takes precedence
    qps: Queries Per Seconds or 0 for no wait/max qps (default 8)
    connections: Number of connections/goroutine/threads (default 4)
    loadOnly: <as it exists today> # no metrics will be collected if this is set to true; requests are still generated
    payloadStr: <any string to be sent as payload> # payload URL takes precedence # new input; switches request type to POST
    payloadURL: <URL as it exists today> # support any payload, not just JSON; e.g., image/png; if both Str and URL are specified, URL takes precedence; switches request type to POST
    contentType: <string content type flag supported by Fortio> # Sets http content type. Switches request type to POST
    versions:
    - name: <as it exists today>
      url: http://sample-app.default.svc:8000
      headers: <as it exists today>
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Enable easier testing of POST APIs (example with payload string, and different content types). Also better load testing features like the ability to set not only qps, but also num parallel connections.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
We plan to simplify the implementation of `metrics/collect`. The parallel go-routines adds minimal value and maximal complexity. We will keep it simple by serializing it. At any rate, the main use-case for this feature is API testing a single version in a (conformance) experiment.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes, please see above.

**How will this feature be tested?**
- [x] POST API based tutorial will include an e2e test
- [x] Task runner unit tests

**How will this feature be documented?**
- [x] Appropriate changes to `metrics/collect` documentation.
- [x] Since some changes here are version breaking, the tutorials need to be modified whenever this feature is introduced into the Iter8 repo
