### ISSUE TITLE
Create a new type of metric: sample

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1008]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Consider an A/B testing use-case where purchase history (e.g., shopping cart $ value) has been stored for versions A and B. Using the entire sample of the purchase history for both A & B will help compute things like confidence values in a much better way (using Iter8's older PBR/OBR algorithms) as opposed to simply using their mean-value for comparing which one is better.

Currently, Iter8 does not have this notion. Only a single point-in-time metric value, which can be either characterized as a gauge metric or a counter metric.

**Describe the feature/solution you'd like**
Create two new types of metrics.
1. Sample metric
2. Histogram metric

Support the following aggregations on sample metrics: mean, count, min, max, percentile-x (where x is any value in the range [0, 100]).

Support the following aggregations on histogram metrics: count, percentile-x (where x is any value in the range [0, 100]).

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Pave the way for confidence computation. Confidence can be computed for the winner, and more fine grained levels (like, confidence with which a given version satisfies a given objective, and so on).

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
The histogram metric is the natural way to store latency histogram collected by Iter8's metrics/collect function. So, we will move away from a one-off-a-kind way compute derived metrics from Fortio towards a more principled way with first-rate CRD support.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
```yaml
  metrics:
  # names must be unique
  - name: elastic/revenue
    description: A sample metric
    provider: prometheus
    params:
    - name: query
      value: >-
       increase(revision_app_request_latencies_count{service_name='${serviceName}'}[${elapsedTime}s])
    versionInfo: # number of versions here need to match number of versions in the experiment object
    - serviceName: hello # version info for each version will be a map
    - serviceName: hello-candidate # version info for each version will be a map
  type: Sample # Sample is a new metric type
  jqExpression: ".data.result[0].value[.]"
  url: http://elastic.search.com
  - name: google-analytics/user-engagement
    description: A histogram metric
    provider: prometheus
    params:
    - name: query
      value: >-
        revision_app_request_latencies_hist{service_name='${serviceName}'}
    versionInfo: # number of versions here need to match number of versions in the experiment object
    - serviceName: hello # version info for each version will be a map
    - serviceName: hello-candidate # version info for each version will be a map
  type: Histogram # Histogram is a new metric type
  jqExpression: ".data.result[0].value[.]"
  url: http://google.analytics.com
```

The above metrics will be stored in the experiment status as described [here](https://github.com/iter8-tools/iter8/issues/961#issuecomment-925936004)

Sample and histogram metrics along with aggregations can be used in objectives and rewards.

```yaml
reward:
  metric: elastic/revenue
  preferredDirection: High
objectives:
- iter8-fortio/latency::percentile-95
  upperLimit: 100.0
- google-analytics/user-engagement::percentile-99.9
  lowerLimit: 65.0
```

**How will this feature be tested?**
- [ ] Unit tests in analytics and controller
- [ ] New experiments that use these functionality, which will be e2e tested

**How will this feature be documented?**
- [ ] Change to metrics and objectives documentation
- [ ] New tutorials/changes to existing ones that highlight these features
