### ISSUE TITLE
Create cronjob template

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1269]
What should be the design of the cronjob template? Here is an example of what a cronjob could look like.

```
# Source: istio-mirroring/templates/k8s.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: RELEASE-NAME-1-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iter8
            image: iter8-tools/iter8:0.9
            imagePullPolicy: Always
            command:
            - "/bin/sh"
            - "-c"
            - |
              iter8 k run --namespace default --group RELEASE-NAME --revision 1
          restartPolicy: Never
      backoffLimit: 0
```
