### ISSUE TITLE
Ensure uniqueness of chartGroup names in autox config

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1334]
**Is your feature request related to a problem? Please describe.**
The current way of specifying the chart group could lead to naming conflicts. Specifically, multiple groups could end up with the same name.

**Solution:**
```yaml
chartGroupName1:
  charts:
    releaseSpec1:
      helmRepo: abc
      chartName: def
      valuesFileUrl: abcdef.com/abcdef
    releaseSpec2:
      helmRepo: ghi
      chartName: jkl
      valuesFileUrl: ghijkl.com/ghijkl
chartGroupName2:
  charts:
    releaseSpec3: 
      helmRepo: mno
      chartName: pqr
      valuesFileUrl: mnopqr.com/mnopqr
```
