### ISSUE TITLE
Enable if conditions in experiment

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1343]
**Is your feature request related to a problem? Please describe.**
We want to write experiments as follows .... 

```shell
iter8 k launch \
--set "tasks={custommetrics,assess,github}" \
--set custommetrics.templates.istio-prom="https://raw.githubusercontent.com/iter8-tools/iter8/master/custommetrics/istio-prom.tpl" \
--set custommetrics.values.destinationWorkload=httpbin \
--set custommetrics.values.destinationWorkloadNamespace=default \
--set assess.SLOs.upper.istio-prom/error-rate=0 \
--set assess.SLOs.upper.istio-prom/latency-mean=100 \
--set github.if=".NumLoops == 10" \
--set github.<other things> \
--set runner=cronjob \
--set cronjobSchedule="*/1 * * * *"
```

**Describe the solution you'd like**
Modify task templates to accept the `if` param in task inputs.

```yaml
{{- if not .token }}
{{- fail "please set a value for the token parameter" }}
{{- end }}
# task: send a GitHub notification
- task: notify
{{- if .if }}
  if: {{ .if | quote }}
{{- end }}
  with:
    url: https://api.github.com/repos/{{ .owner }}/{{ .repo }}/dispatches
    method: POST
    headers:
      Authorization: token {{ .token }}
      Accept: application/vnd.github+json
    payloadTemplateURL: {{ default "https://raw.githubusercontent.com/iter8-tools/iter8/v0.11.10/charts/iter8/templates/_payload-github.tpl" .payloadTemplateURL }}
    softFailure: {{ default true .softFailure }}
{{ end }}
```
