### ISSUE TITLE
Allow `if` clause in tasks

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1357]
**Is your feature request related to a problem? Please describe.**
The `github` and `slack` tasks support the conditional `if` statement. Other tasks should as well.

**Additional context**
In the existing tasks, it was sufficient to add the `if` clause as follows:

```yaml
- task: notify
{{- if .if }}
  if: {{ .if | quote }}
{{- end }}
```

However, in tasks that implement the content of the `with` statement using something like: 

```yaml
with:
{{ . | toYaml | indent 4 }}
```

will also need to remove the if statement:

```yaml
with:
{{ omit $ "if" | toYaml | indent 4 }}
```
