### ISSUE TITLE
Create helm chart for Iter8 traffic controller

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1419]
A challenge in running experiments is configuration of traffic to more than one version of an app/ML model. Iter8 has traditionally taken the approach that the experimenter is responsible for configuring the routing before running the experiment. 

The Iter8 traffic controller is a Kubernetes controller designed to assist configuration of traffic for testing. It allows users a declarative way to describe the desired configuration and automates its implementation.

**Describe the solution you'd like**
A helm chart to install the Iter8 traffic controller. This chart is similar in purpose to the `abn` and `autox` helm charts we already have. However, instead of using a `Deployment` resource, we should use a `StatefulSet`. Furthermore, since it is a controller, no `Service` should be required. 

The chart is configured using a values file of the form 

```yaml
defaultResync: 30s
resourceTypes:
  deploy:
    group: apps
    version: v1
    resource: deployments
  svc:
    group: ""
    version: v1
    resource: services
  isvc:
    group: serving.kserve.io
    version: v1beta1
    resource: inferenceservices
  vs:
    group: networking.istio.io
    version: v1beta1
    resource: virtualservices
```
