### ISSUE TITLE
Design Metrics (HTTP) server for serving metrics data for Grafana dashboard

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1512]
The Grafana dashboard, currently being developed to display metrics data for A/B/n, needs a way to obtain metrics data.

Consider creating a separate service that is dedicated to serving metrics for Grafana dashboard.

Under the covers, this server should invoke the `GetMetrics()` function (see [here](https://github.com/iter8-tools/iter8/blob/6a9bde9dbc700a4a58d15cb2301f7aef4def19dc/controllers/storageclient/interface.go#L50)).

Part of epic https://github.com/iter8-tools/iter8/issues/1501

**Comment by kalantar** [comment]
Grafana requires the following from  HTTP service:

1. get all applications. Expect that appliciation can be specified in dashboard URL. If not, need this.  _future requirement_
2. get all versions for a given application - returns list of versions. _future requirement_
3. get all metrics data for a given app, list of versions - expects result from latest signatures - returns 2 lists for each requested version: all metrics over all users and all metrics over transactions. Internally, this calls `storage.GetMetrics(app, version)`; if list of versions is empty, return for all versions
4. get summary metrics for a given app, list of versions - expects result from latest signatures - returns 2 lists for each requested version: all metrics over all users and all metrics over transactions. Internally, this calls `storage.GetSummaryMetrics(app, version)`; if list of versions is empty, return for all versions

Notes/Questions
- `storage.GetMetrics()` api defined in https://github.com/iter8-tools/iter8/pull/1511
- `storage.GetSummaryMetrics()` api defined in https://github.com/iter8-tools/iter8/blob/6a9bde9dbc700a4a58d15cb2301f7aef4def19dc/controllers/storageclient/badgerdb/simple.go#L183
- Should `storage.GetSummaryMetrics()` continue to compute the summary metrics or move to http service?   _leave it for now_
- Result of rest calls should mirror result of internal implementation as closely as possible.

Next Steps
- define REST APIs
- learn how to define HTTP service

**Comment by kalantar** [comment]
See below for updated design
~~Grafana dashboard requests data from Iter8 (HTTP) Metrics Service.~~
~~Data source is Iter8 Metrics service endpoint.~~

### ~~Metrics Service APIs:~~

#### ~~1. GET /metrics?application=app-name~~
##### Result (Content-Type: application/json):
```yaml
{
  "my-app": {
    "0": {
      "numUsers": k,
      "metric1": {
        "metricsOverTransactions": [],
        "metricsOverUsers": [],
        "summaryOverTransactions": {"count": n, "mean" mean, "stddev"": stddev, "min": min, "max": max}
        "summaryOverUsers": {"count": n, "mean" mean, "stddev"": stddev, "min": min, "max": max}
      },
      "metric2": {}, ...
    },
    "1": {}, ...
  }
}
```

##### ~~Response codes:~~
- **200** - ok
- **400** - request not valid JSON
- **404** - no such application
- **405** - method not allowed
- **500** - error processing request

##### ~~Implementation:~~
```shell
Find routemap from application name
For each version in routemap
  if version in request list (or request list is empty)
    call storage.GetMetrics(application, version, version.Signature)
    call stroage.GetSummaryMetrics(application, version, version.Signature)
Combine results
```

### ~~Comments~~
~~1. Computation of summary metrics still in storage client -- plan leave it for now (alternative is to move it to metrics service)~~
