### ISSUE TITLE
Summary Data not shown when only 1 version

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1533]
If we have 2 possible versions and only 1 is available, the metrics service currently returns a null for the summary metric:

```yaml
      "SummaryOverTransactions": [
         {
            "Version": 0,
            "Count": 148,
            "Mean": 45.70898656756755,
            "StdDev": 27.50946164746194,
            "Min": 1.840404,
            "Max": 99.833308
         },
         null
      ],
      "SummaryOverUsers": [
         {
            "Version": 0,
            "Count": 56,
            "Mean": 120.98089307142855,
            "StdDev": 86.54687524133293,
            "Min": 2.246336,
            "Max": 332.47791600000005
         },
         null
      ]
```

Grafana does not handle this. No summary is shown. Can this be fixed in Grafana or does the metrics service need to change?  

Histograms are fine.
