### ISSUE TITLE
"iter8-tools/host": must be no more than 63 characters

### ISSUE THREAD

**Issue by haf-tech** [iter8-tools/iter8#235]
Description
Experiment fails if the host is too long

Details
`tekton-101-iter8-v1-experiment   Pause   RoutingRulesError: UnexpectedCondition: unable to parse requirement: invalid label value: "istio-ingressgateway-istio-system.apps.cluster-0000.sandbox1493.opentlc.com": at key: "iter8-tools/host": must be no more than 63 characters , Experiment Pause   tekton-101-v1   0            tekton-101-v1   0`

and yaml
```
# iter8: Initial Experiment
apiVersion: iter8.tools/v1alpha1
kind: Experiment
metadata:
  name: tekton-101-iter8-v1-experiment
spec:
  targetService:
    kind: Service
    # service name
    #name: tekton-101-v1
    baseline: tekton-101-v1
    candidate: tekton-101-v1
    hosts:
      - name: istio-ingressgateway-istio-system.apps.cluster-0000.sandbox1493.opentlc.com
        gateway: tekton-101-gateway
  trafficControl:
    strategy: check_and_increment
    interval: 10s
    trafficStepSize: 90
    maxIterations: 1
    maxTrafficPercentage: 90
  analysis:
    analyticsService: "http://iter8-analytics.iter8:8080"
```

Additional
Why is it not possible to support wildcard hosts? Otherwise the support to define uri matcher for the VS would be also helpful.
