### ISSUE TITLE
Supporting arbitrary user defined virtual services

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#268]
Problem: How to support arbitrary VSes (e.g., with timeout retry values / match clauses / ...) in iter8's CRD

Proposal: Consider the following virtual service.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
  namespace: demo
spec:
  hosts:
  - test1
  gateways:
  - test-gateway  
  http:
    - match:
        - headers:
            apikey:
              exact: 111
        - headers:
            apikey:
              exact: 222
        - uri:
            prefix: /path1/
        - uri:
            prefix: /path2/
      rewrite:
        uri: /newpath/v1/
        authority: test2
      route:
        - destination:
            host: test2
    - match:
        - headers:
            apikey:
              exact: 333
      route:
        - destination:
            host: test2
            subset: v1
          headers:
            response:
              remove:
              - foo
    - fault:
        abort:
          httpStatus: 444
          percent: 100
      route:
      - destination:
          host: test3
```

When creating an iter8 experiment spec, we can require the user to provide a reference to this virtual service, **along** with the appropriate route index. For e.g., the index in this case could be `1` which indicates that iter8 will leave the rest of the VS alone and will only manipulate the route where `apikey == 333`. Further, for subset v1, it will leave the header manipulation logic untouched, and only play with the weights. After an iteration in iter8, the same VS above could like the following.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
  namespace: demo
spec:
  hosts:
  - test1
  gateways:
  - test-gateway  
  http:
    - match:
        - headers:
            apikey:
              exact: 111
        - headers:
            apikey:
              exact: 222
        - uri:
            prefix: /path1/
        - uri:
            prefix: /path2/
      rewrite:
        uri: /newpath/v1/
        authority: test2
      route:
        - destination:
            host: test2
    - match:
        - headers:
            apikey:
              exact: 333
      route:
        - destination:
            host: test2
            subset: v1
            weight: 25
          headers:
            response:
              remove:
              - foo
        - destination:
            host: test2
            subset: v2
            weight: 75
    - fault:
        abort:
          httpStatus: 444
          percent: 100
      route:
      - destination:
          host: test3
```

@kimikowang @kalantar Doesn't this approach work with user supplied / pre-existing virtual services (referenced in iter8 experiment spec) -- at least for deployment based experiments (if not service based experiments)? My understanding is that it will also work for both edge services and services not exposed to the external world. Isn't this so?
