### ISSUE TITLE
Prelimnary CR/CRD for Iter8 metrics Configmap

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8#273]

**Comment by sushmarchandran** [comment]
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: iter8-metrics.iter8.tools
spec:
  group: iter8.tools
  names:
    kind: Iter8Metric
    listKind: Iter8MetricList
    plural: iter8-metrics
    singular: iter8-metric
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Metric contains the sections for defining a metric for iter8 experiments,
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Iter8Metric Spec defines the desired state of iter8-metrics
          properties:
            counterMetrics:
              description: 'List of counter metric definitions to be used in iter8 experiments'
              properties:
                name:
                  description: 'Name of the counter metric that is being defined'
                  type: string
                displayName:
                  description: 'Name of the counter metric that will be used in UI interfaces'
                  type: string
                queryTemplate:
                  description: 'Prometheus Query Template to retrieve a value for this metric'
                  type: string
                #preferredDirection must be specified in order to use thresholds
                preferredDirection:
                  description: 'Indicates preference for metric values -- lower, higher, or None (default)'
                  enum:
                  - higher
                  - lower
                  - none
                  type: string
                Units:
                  description: 'Unit for measuring this metric'
                  type: string
              required:
              - name
              - queryTemplate
              type: array
            ratioMetrics:
              description: 'List of ratio metric definitions to be used in iter8 experiments'
              properties:
                name:
                  description: 'Name of the ratio metric that is being defined'
                  type: string
                displayName:
                  description: 'Name of the ratio metric that will be used in UI interfaces'
                  type: string
                numerator:
                  description: 'Fully qualified name of a counter metric to be used as numerator for calculating the value of this ratio metric'
                  type: string
                denominator:
                  description: 'Fully qualified name of a counter metric to be used as numerator for calculating the value of this ratio metric'
                  type: string
                preferredDirection:
                  description: 'Indicates preference for metric values -- lower, higher, or None (default)'
                  enum:
                  - higher
                  - lower
                  - none
                  type: string
                Units:
                  description: 'Unit for measuring this metric'
                  type: string
                zeroToOne:
                  description: Boolean flag indicating if the value of this metric is always in the range 0 to 1
                  type: boolean
              required:
              - name
              - numerator
              - denominator
              type: array
          type:
            object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

**Comment by sushmarchandran** [comment]
@kimikowang @sriumcp Initial CRD for the iter8 metrics. Let me know what you think.

**Comment by sushmarchandran** [comment]
Sample CR:
```
apiVersion: "iter8.tools/v1alpha2"
kind: Iter8Metric
metadata:
  name: sample
spec:
  counterMetrics:
    - name: 'iter8_total_latency'
      displayName: 'Total latency'
      queryTemplate: 'sampleQueryTemplate'
    - name: 'iter8_request_count'
      displayName: 'Request Count'
      queryTemplate: 'sampleQueryTemplate'
  ratioMetric:
    - name: 'iter8_mean_latency'
      displayname: 'Mean latency'
      numerator: 'iter8_total_latency'
      denominator: 'iter8_request_count'
```

**Comment by kimikowang** [comment]
@sushmarchandran Thanks for the sample, I have several comments and questions:
1. Storing the metrics in a map may help look up and get metrics easier.
2. How/Where are the query templates defined?
3. How will the custom metrics be defined?

**Comment by sushmarchandran** [comment]
@kimikowang 
1. It is stored in the form of a map. There are two keys- counter and ratio metrics and each of those will have a list of metrics. How would this change according to what you're saying?
2. The query templates are defined only for counter metrics under the `queryTemplates` section you can see in the CRD.
3. Custom metrics can be defined in the exact same way I have defined the iter8 metrics in the CR in my previous comment.
For example:
```
apiVersion: "iter8.tools/v1alpha2"
kind: Iter8Metric
metadata:
  name: sample
spec:
  counterMetrics:
    - name: 'custom_metric'
      displayName: 'Custom latency'
      queryTemplate: 'sampleQueryTemplate'
    - name: 'iter8_request_count'
      displayName: 'Request Count'
      queryTemplate: 'sampleQueryTemplate'
  ratioMetrics:
    - name: 'iter8_custom_latency'
      displayname: 'Custom latency'
      numerator: 'custom_metric'
      denominator: 'iter8_request_count'
```

**Comment by sriumcp** [comment]
Adding to the above: here is how controller ships these metrics to analytics service today: https://github.com/iter8-tools/iter8-analytics/blob/master/iter8_analytics/api/analytics/types.py

```
class DirectionEnum(str, Enum): # directions for metric values
    lower = "lower"
    higher = "higher"

class MetricSpec(BaseModel):
    id: iter8id = Field(..., alias = "name", description="ID of the metric")
    preferred_direction: DirectionEnum = Field(None, description="Indicates preference for metric values -- lower, higher, or None (default)")
    # this will be used in KUI / Kiali / controller status fields
    descriptive_short_name: str = Field(None, description = "Descriptive short name")

    class Config:
        allow_population_by_field_name = True

# counter metric defined in iter8 configmaps
class CounterMetricSpec(MetricSpec):
    query_template: str = Field(...,
                                     description="Prometheus query template")

class RatioMetricSpec(MetricSpec):  # ratio metric = numerator counter / denominator counter
    numerator: str = Field(
        ..., description="ID of the counter metric used in numerator")
    denominator: str = Field(
        ..., description="ID of the counter metric used in denominator")
    zero_to_one: bool = Field(
        False, description="Boolean flag indicating if the value of this metric is always in the range 0 to 1")

class MetricSpecs(BaseModel):
    counter_metrics: Sequence[CounterMetricSpec] = Field(..., description = "All counter metric specs")
    ratio_metrics: Sequence[RatioMetricSpec] = Field(..., description = "All ratio metric specs")
```

To me, it looks like 1:1 match between the CR and data format used by controller to ship it to analytics. Perhaps, the id field should be the fully qualified name of the metric (e.g., iter8_custom_latency.sample.<namespace where metric cr is defined>?

**Comment by kimikowang** [comment]
@sushmarchandran 

Oh I see, so the content of `sampleQueryTemplate` is embedded in analytics. 

My idea is let `counterMetrics` or `ratioMetrics` points to a map. We can use the metric name as key and other attributes as value:
```
spec:
  counterMetrics:
    "iter8_total_latency": 
        displayName: 'Total latency'
        queryTemplate: 'sampleQueryTemplate'
    "iter8_request_count":
        displayName: 'Request Count'
        queryTemplate: 'sampleQueryTemplate'
```

**Comment by sriumcp** [comment]
@kimikowang What is the advantage of the map representation of the list representation?

**Comment by kimikowang** [comment]
> @kimikowang What is the advantage of the map representation over the list representation?
> 
> It does seem more compact -- so perhaps less typing for the user?

To reduce computation complexity. Think about when we want to use `iter8_total_latency` in an experiment. After reading the metric cr, the controller needs to get the content of the metric. If this is a list, we need to go over the whole list to find it(O(N)). But for a map, it's just a O(1) complexity.

**Comment by sriumcp** [comment]
Really good point. Makes sense.

As of now, controller sends the entire ConfigMap to analytics. But I agree, this will change once this feature is implemented, and controller should probably pick and choose and send only the relevant (counter and ratio) metrics that are part of the experiment.

**Comment by sushmarchandran** [comment]
@sriumcp @kimikowang 
Updated CRD:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: iter8-metrics.iter8.tools
spec:
  group: iter8.tools
  names:
    kind: Iter8Metric
    listKind: Iter8MetricList
    plural: iter8-metrics
    singular: iter8-metric
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Metric contains the sections for defining a metric for iter8 experiments,
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Iter8Metric Spec defines the desired state of iter8-metrics
          properties:
            counterMetrics:
              description: 'List of counter metric definitions to be used in iter8 experiments'
              properties:
                name:
                  description: 'Name of the counter metric that is being defined'
                  properties:
                    displayName:
                      description: 'Name of the counter metric that will be used in UI interfaces'
                      type: string
                    queryTemplate:
                      description: 'Prometheus Query Template to retrieve a value for this metric'
                      type: string
                    #preferredDirection must be specified in order to use thresholds
                    preferredDirection:
                      description: 'Indicates preference for metric values -- lower, higher, or None (default)'
                      enum:
                      - higher
                      - lower
                      - none
                      type: string
                    Units:
                      description: 'Unit for measuring this metric'
                      type: string
                  required:
                  - queryTemplate
                  type: object
                  format: string
              type: object
            ratioMetrics:
              description: 'List of ratio metric definitions to be used in iter8 experiments'
              properties:
                name:
                  description: 'Name of the ratio metric that is being defined'
                  properties:
                    displayName:
                      description: 'Name of the ratio metric that will be used in UI interfaces'
                      type: string
                    numerator:
                      description: 'Fully qualified name of a counter metric to be used as numerator for calculating the value of this ratio metric'
                      type: string
                    denominator:
                      description: 'Fully qualified name of a counter metric to be used as numerator for calculating the value of this ratio metric'
                      type: string
                    preferredDirection:
                      description: 'Indicates preference for metric values -- lower, higher, or None (default)'
                      enum:
                      - higher
                      - lower
                      - none
                      type: string
                    Units:
                      description: 'Unit for measuring this metric'
                      type: string
                    zeroToOne:
                      description: Boolean flag indicating if the value of this metric is always in the range 0 to 1
                      type: boolean
                  required:
                  - numerator
                  - denominator
                  format: string
                  type: object
              type: object
          type:
            object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```
Updated sample CR:
```
apiVersion: 'iter8.tools/v1alpha2'
kind: Iter8Metric
metadata:
  name: sample
spec:
  counterMetrics:
    'iter8_total_latency':
      displayName: 'Total latency'
      queryTemplate: 'sampleQueryTemplate'
    'iter8_request_count':
      displayName: 'Request Count'
      queryTemplate: 'sampleQueryTemplate'
  ratioMetrics:
    'iter8_mean_latency':
      displayname: 'Mean latency'
      numerator: 'iter8_total_latency'
      denominator: 'iter8_request_count'
```
