### ISSUE TITLE
[Feature Request] Support for Sysdig and other DBs with POST request

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8#586]
**Is your feature request related to a problem? Please describe.**
Some databases like sysdig and elastic use POST APIs for metric queries. We want to support metrics with POST APIs in iter8 experiments.

**Why is the feature useful for Iter8 users?**
This will enable users to incorporate metrics from Sysdig, elastic and other such DBs with POST APIs in their experiments.

**Describe the solution you'd like**
Currently, `metrics` resources do not provide a HTTP `method` field. Provide one and support both `GET` and `POST`. This  field is optional and will be defaulted to `GET` if not supplied.

**Describe alternatives you've considered**
There are really no alternatives. POST APIs can only be accessed with POST! 

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**

Consider **metric 1** defined as follows.

```yaml
apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: request-count
spec:
  params:
  - name: query
    value: |
      sum(increase(revision_app_request_latencies_count{revision_name='$revision'}[$elapsedTime])) or on() vector(0)
  description: Number of requests
  type: counter
  provider: prometheus
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://prometheus-operated.iter8-system:9090/api/v1/query
```

Now, consider **metric 2** defined as follows.

```yaml
apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: request-count
spec:
  params:
  - name: query
    value: |
      sum(increase(revision_app_request_latencies_count{revision_name='$revision'}[$elapsedTime])) or on() vector(0)
  description: Number of requests
  type: counter
  method: GET
  provider: prometheus
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://prometheus-operated.iter8-system:9090/api/v1/query
```

GET is the currently supported implementation... in both the above cases, Iter8 will currently (and will continue to) query the metric  DB as follows.

```python
requests.get('http://prometheus-operated.iter8-system:9090/api/v1/query', params=params)
```

Consider **metric 3** defined as follows.
```yaml
apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: request-count
spec:
  body: |
    {
      "last": $elapsedTime,
      "metrics": [
        {
          "id": "ibm_codeengine_application_request_count{revision_name='$revision'}"
        }
      ],
      "filter": "ibm_location = \"us-south\""
    }
  method: POST
  description: Number of requests
  type: counter
  provider: sysdig
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://sysdig.com
```

Iter8 will now query the metric DB as follows.

```python
body =  {
      "last": 300, // current value of elapsedTime
      "metrics": [
        {
          "id": "ibm_codeengine_application_request_count{revision_name='revision-1'}"// current value of revision
        }
      ],
      "filter": "ibm_location = \"us-south\""
    }
requests.get('http://sysdig.com', body = body)
```

**How will this feature be tested?**
Unit tests in the Iter8 analytics repo for various metric providers and GET/POST based metrics.

**How will this feature be documented?**
Update reference for metrics CRD.
Code-samples that demonstrate use of metrics with GET and POST methods with the appropriate databases.

**Additional context**
Sample Sysdig Query using curl:
`curl -X POST https://us-south.monitoring.cloud.ibm.com/api/data -H "Authorization: Bearer $SYSDIGTOKEN" -H "content-type: application/json" -d @metrics.json`
metrics.json:
```
{
  "last": 300,
  "metrics": [
    {
      "id": "ibm_codeengine_application_service_count"
    }
  ],
  "filter": "ibm_location = \"us-south\""
}
```
