### ISSUE TITLE
[Feature Request] Enable support for different types of metric database authentication

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#588]
**Is your feature request related to a problem? Please describe.**
Currently, Iter8 supports a low-level header based authentication when querying metrics databases. REST APIs have standardized authentication mechanisms, namely, Basic Auth, API Tokens, and Bearer Token. We want to support these.

**Why is the feature useful for users of Iter8?**
This feature will enable Iter8 experiments with databases that require authentication, like Prometheus, Sysdig, New Relic, and elastic.

**Describe the solution you'd like**
Introduce `authType` in metrics CRD as illustrated below. The relevant etc3 issue is [here](https://github.com/iter8-tools/etc3/issues/195). 
Enable iter8-analytics to pick up authentication secrets from the referenced secret, as illustrated below. The relevant iter8-analytics issue is [here](https://github.com/iter8-tools/iter8-analytics/issues/262).

**Describe alternatives you've considered**
Raw header based mechanisms supported as of now... low-level and not easy to use.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, provide it below.**
**Note:** The following examples illustrate authentication for GET requests. Similar concepts apply for POST requests as well.

### Basic auth example
*Reference:* https://swagger.io/docs/specification/authentication/basic-authentication/
*Reference:* https://docs.python-requests.org/en/master/user/authentication/#basic-authentication

Suppose we define a metric as follows.
```yaml
apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: request-count
spec:
  params:
  - name: query
    value: |
      sum(increase(revision_app_request_latencies_count{revision_name='$revision'}[$elapsedTime])) or on() vector(0)
  description: Number of requests
  type: counter
  authType: basic
  secret: default/basicsecret
  provider: prometheus
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://prometheus-operated.iter8-system:9090/api/v1/query
```

Further,  suppose we create the secret referenced in the above metric as follows: 

```shell
kubectl create secret generic basicsecret --type=basic-auth --from-literal=username=admin --from-literal=password=t0p-secret
```

Iter8 will then query this metric as follows:

```python
requests.get('http://prometheus-operated.iter8-system:9090/api/v1/query', params=params, auth=('admin', 't0p-secret'))
```

### API Key example
*Reference:* https://swagger.io/docs/specification/authentication/api-keys/

Suppose we define a metric as follows.
```yaml
apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: request-count
spec:
  params:
  - name: query
    value: |
      sum(increase(revision_app_request_latencies_count{revision_name='$revision'}[$elapsedTime])) or on() vector(0)
  description: Number of requests
  type: counter
  authType: apikey
  secret: default/apikey
  headerTemplates:
    X-API-Key: $mykey
  provider: newrelic
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://newrelic.com
```

Further,  suppose we create the secret referenced in the above metric as follows: 

```shell
kubectl create secret generic apikey --type=opaque --from-literal=mykey=1234abcd5678
```

Iter8 will then query this metric as follows:

```python
headers = {'X-API-key': '1234abcd5678'}
requests.get('http://newrelic.com', params=params, headers=headers)
```

### Bearer token example
*Reference:* https://swagger.io/docs/specification/authentication/bearer-authentication/

Suppose we define a metric as follows.
```yaml
apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: request-count
spec:
  params:
  - name: query
    value: |
      sum(increase(revision_app_request_latencies_count{revision_name='$revision'}[$elapsedTime])) or on() vector(0)
  description: Number of requests
  type: counter
  authType: bearer
  secret: default/token
  provider: newrelic
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://sysdig.com
```

Further,  suppose we create the secret referenced in the above metric as follows: 

```shell
kubectl create secret generic token --type=opaque --from-literal=token=1234abcd5678
```

Iter8 will then query this metric as follows:

```python
headers = {'Authorization': `Bearer 1234abcd5678'}
requests.get('http://sysdig.com', params=params, headers=headers)
```

**What tests will you create for this feature?**
All features will be unit tested at iter8-analytics, using HTTP request-mock and python mock; the latter is useful for mocking K8s APIs for secrets.

**What documentation will you create for this feature?**
1. Update reference for metrics CRD
2. Code-samples that demonstrate use of various types of authentication with the appropriate databases.

**Additional context**
Prometheus and Elastic require basic auth.
Sysdig and New Relic require API tokens.

**References:**
1. http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
2. https://docs.python-requests.org/en/master/user/authentication/
3. https://www.loginradius.com/blog/async/everything-you-want-to-know-about-authorization-headers/
4. https://en.wikipedia.org/wiki/Basic_access_authentication
5. https://swagger.io/docs/specification/authentication/
