### ISSUE TITLE
[Feature Request] Make fortio duration infinite in tests and finite in tests

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#617]
**Is your feature request related to a problem? Please describe.**
Fortio runs  for 120s and quits which is a problem while running  tutorials. User might want to get a coffee between fortio.yaml apply and experiment.yaml apply! 

**Describe the solution you'd like**
Change fortio.yaml in tutorials files as follows.
```
command: ["fortio", "load", "-t", "$(DURATION)s", "-json", "/shared/fortiooutput.json", $(URL)]
        env:
        - name: URL
          value: URL_VALUE
        - name: DURATION
          value: 60000 # 120 in tests
```

Similar concern exists for `curl.yaml` files as well... they need to also be fixed accordingly.

**Why is the feature useful for Iter8 users?**
This feature will mitigate timing issues when a user tries out the tutorials. 

**Describe alternatives you've considered**
Combine traffic generation and experiment creation steps... this makes the experiment.yaml not stand out (which is something that is nice to have)

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Slack discussion... captured in the solution above.

**How will this feature be tested?**
[ ] Tests already exist that utilize fortio.yaml. They need to patched so that duration value equals some small number (120) instead of a large number (60000)

**How will this feature be documented?**
This is not a core feature requiring documentation. However,  "look inside fortio.yaml" will need to show the new fortio files.
