### ISSUE TITLE
Need better documentation for metrics/collect

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8#770]
This page (https://iter8.tools/0.6/reference/tasks/metrics/#version) needs to be more clear about creating multiple "versions" of workload generator, one for each version. 

```
      - task: metrics/collect
        with:
          versions:
          - name: iter8-app
            url: http://iter8-app.default.svc:8000
          - name: iter8-app-candidate
            url: http://iter8-app-candidate.default.svc:8000
```

The above would be a useful example to include in the documentation, as an experiment is mostly about evaluating 2 or more versions.
