### ISSUE TITLE
Improve trafficControl clarity

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8#79]
When I was going through the Iter8 demo, I thought I understood this section of an Experiment CR:
```
  trafficControl:
    strategy: check_and_increment
    interval: 30s
    trafficStepSize: 20
    maxIterations: 8
    maxTrafficPercentage: 80
```
This to me at first glance was to increase traffic volume by 20% every 30 seconds up to 80%, and if everything looks good, traffic will completely be shifted to the candidate version. However, if something goes wrong, controller will try a maximum of 8 iterations before giving up. 

After running the demo a few times, I noticed even when things go smoothly, it still takes all 8 iterations before controller switches all traffic to the candidate version. After it was explained to me what is the reason for this design, it made sense. But maybe changing `maxIterations` to `mandatoryIterations` (or something to that effect) would help clarify its true meaning, or at least confuse users enough that they would look up the documentation to understand its meaning.
