### ISSUE TITLE
Provide a task to issue http requests

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#845]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Integration with GitHub actions or GitOps requires an ability to trigger actions executed elsewhere. Provide a way to make http (post) requests.

**Describe the feature/solution you'd like**
support action with following inputs:

```yaml
task: common/http-request
with:
    url: // url to which request can be sent; required; may contain placeholders
    method: // either POST (default) or GET
    authtype: // default none; valid values are Basic, Bearer and APIKey
    secret: // namespace/name of secret; if ns missing uses ns of experiment; not required; used for placeholder substitution
    headers: // list of name/value where name is header to add to request, values may contain placeholders; not required
    body:  // content of message to send. would typically be expresses in json; may use placeholders; not required; default under discussion below
```

URL is required. 
Default Method is POST (also possible is GET). 
authtype is one of Basic, Bearer or APIKey. Default is none.
Secret is namespace/name of a secret that contains any keys
headers is name values

URL, headers and body can all have interpolated values from secret and from the experiment

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Users can integrate with github actions, argo cd etc

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Discuss in this issue.

**How will this feature be tested?**
- [ ] test against postman-echo.com

**How will this feature be documented?**
- [ ] task documentation in reference section of iter8.tools

**Comment by sriumcp** [comment]
@kalantar Most of this looks good.. 

1. Could you please YAML-ize the sample above (instead of dumping the go struct) -- the GO struct makes it a bit less obvious what the UX would be. This is just an edit to the issue.

2. I think a JSON body with the current experiment object in it is preferable to a string body...  at any rate, it would be better if JSON experiment is sent as the body by default; if at all we want to support a templated string body, it needs to be optional (and not the default option). Things like GH actions and Tekton triggers can easily pick fields off of the JSON body (for example, stuff like whether there is a winner and which version won and what the weights are). Specifically, in GH actions, this can be done using jq. I believe Tekton provides something equivalent to extract params out of incoming webhooks.

A string body not only makes the post processing complex, it also puts the burden of designing the string on the user.

I would design the body (by default to be JSON with the following two fields)
```yaml
body:
  summary:
    winnerFound: true
    winner:...
    versionRecommendedForPromotion: ...
    weights:
  experiment: <the current experiment object>
```

This makes the incoming webhook actionable.

3. Go has excellent support for HTTP mocks and testing. This is a good place to use interfaces. See this blog post for example -- https://www.thegreatcodeadventure.com/mocking-http-requests-in-golang/ -- the mock would allow you to test the content of the HTTP requests instead of merely testing if the task completed without crashing / panic (please add this to the section on how this feature will be tested). 
***
Incidentally, in my experience, mocking in go unit tests certainly needs a bit of thought. For example, the recent readiness task that I pushed -- I created it in a day, but had to take another day to rewrite it (since I had to think through the design and implementation so that it is friendly for mocking), and yet another day to create the iter8.tools documentation for it.

**Comment by kalantar** [comment]
+1 for suggested default body.

**Comment by sriumcp** [comment]
Actually -- https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-using-the-rest-api

I am wondering if there's a way to customize the JSON body. Note that you can supply inputs to the GH action as part of webhook events (as described in the last section of the link above and also the links contained in that section).

**Comment by sriumcp** [comment]
Also @kalantar 

The stated goal of this feature is use with GH action.

Could you also briefly describe how this task can be used to achieve the following? For 1 and 2, what would the task in the experiment look like, and what would the inputs to the GH action look like? For 3, what would the task in the experiment look like?

1. Send a notification, so that a GH action can promote the version recommended for promotion (in the Helm values file)
2. Send a notification so that a GH action can adjust weights (in the Helm values file)
3. Send a notification (to wherever) in CloudEvents format: https://github.com/cloudevents/spec/blob/master/spec.md#example (cloud events has native support in Tekton and Knative eventing AFAIK).

I am obviously interested in the above capabilities due to the upcoming Knative talk with Helm / GH actions pitch in it :) It goes without saying that the questions are more broadly applicable.

**Comment by sriumcp** [comment]
After reading through CloudEvents documentation, I wonder if the schema for the task should include --

bodyFormat: oneOf(default | string | GitHub Actions | CloudEvents)

This would enable us to create more formats in the future, for example,  CloudEventsForKNativeEventing, CloudEventsForKeptn and so on.

GitHub Actions format can wrap the data within inputs and could include the (mandatory) ref section (as defined in the docs above).

**Comment by kalantar** [comment]
>     1. Could you please YAML-ize the sample above (instead of dumping the go struct) -- the GO struct makes it a bit less obvious what the UX would be. This is just an edit to the issue.

Updated.

**Comment by kalantar** [comment]
> I am wondering if there's a way to customize the JSON body. Note that you can supply inputs to the GH action as part of webhook events (as described in the last section of the link above and also the links contained in that section).

The current approach of a string body allows the user to put anything. In particular, JSON that can be customized. See the [initial documentation for the current implementation](https://github.com/iter8-tools/iter8/pull/847) that shows how to dispatch a GH action. This example shows dispatching an action that expects two parameters. In particular, I tested it on this action:

```yaml
name: Hello
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{github.event.inputs.name}}"
        echo "- in ${{github.event.inputs.home}}"
```

**Comment by kalantar** [comment]
The action as it is defined is meant to be general; it can be used to support any request. We may want to consider specialized implementations (that reuse it) specific for specific purposes such as GH actions instead of trying to make the body be support everything.

**Comment by sriumcp** [comment]
```yaml
          body: |
             {
               "ref":"master", 
               "inputs":{
                 "name": "{{.this.metadata.name}}",
                 "home":"{{.this.metadata.namespace}}"
               }
             }
```

From your documentation... this is interesting. So, just to be sure, we **can** use the existing implementation to send any JSON body ... correct? And the JSON body itself is templated ... correct?

What I found interesting is that ... you are actually specifying a string body, but because of the curly braces in the template, it gets converted into a JSON object during JSON marshal (please let me know if I got this wrong).

**Comment by kalantar** [comment]
> What I found interesting is that ... you are actually specifying a string body, but because of the curly braces in the template, it gets converted into a JSON object during JSON marshal (please let me know if I got this wrong).

It will not be converted to a JSON object in marshal. There is no need. It is being sent as the body of a message. Most POST messages containing JSON are just JSON strings/files like this. The content-type header identifies what the receiver should do with it.  Our implementation defaults this to `application/json` but a user could override this.

**Comment by kalantar** [comment]
I suggest we start with this general task. We can make progress towards demo and gain some experience. And then consider creating github/action and notification/cloudevent if we feel that having more specific tasks that eliminate the need for the user to specify most of these things makes sense. I think it does and creating them becomes easier on top of this one.

We probably  do still need a default body though.

**Comment by sriumcp** [comment]
Ok.... all of the above sounds good to me. 

I am simply trying to understand how you got this to work with GH actions. GH actions trigger expects JSON body as input while your task emits body as a string (instead of JSON obj). Some magic has to happen during serialization of the body, right?

In particular, you did not do:
```yaml
body:
  ref: 
  inputs: 
```

instead you did:

```yaml
body: |
  {
    "ref": ...
    "inputs": ...
  }
```

The GH action seems to be happy with 2 above instead of 1. I am wondering how...
