### ISSUE TITLE
RequestCount appears twice in CRD status->..->aggregatedMetrics

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/iter8#849]
**Describe the bug**
In Experiment CRD->status->Analysis->aggregatedMetrics, requestCount was listed twice with different value 

```
status:
  analysis:
    aggregatedMetrics:
      data:
        iter8-istio/error-rate:
          data:
            productpage-v1:
              value: "0"
            productpage-v2:
              value: "0"
        iter8-istio/mean-latency:
          data:
            productpage-v1:
              value: 229794917681n
            productpage-v2:
              value: 148935671588n
        iter8-istio/request-count:
          data:
            productpage-v1:
              value: 1468318318319n
            productpage-v2:
              value: 878941005699n
        iter8-istio/user-engagement:
          data:
            productpage-v1:
              value: 15292910334n
            productpage-v2:
              value: 20588925674n
        request-count:
          data:
            productpage-v1:
              value: 1478306878307n
            productpage-v2:
              value: 884534537194n
```

**To Reproduce**
Follow the Quick start tutorial for Istio, create the experiment using `Hybrid (A/B + SLOs) testing`

**Expected behavior**
requestCount should only appeared once.

**Kubernetes stack (please provide the following information):**
 - K8s environment: Minikube (driver: docker)
 - K8s version : 1.21.2
 - K8s stack: Istio (1.10.1)
