### ISSUE TITLE
Making versionInfo in the experiment CRD less confusing

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#862]
**Is your feature request related to a **problem**? Please describe the **problem**.**
In Helmex (like [this](https://iter8.tools/0.7/getting-started/first-experiment/)), you have a *baseline* and *candidate* version defined in the Helm chart, and  a conformance experiment for the candidate version. The conformance experiment has versionInfo section which has a single version called baseline ... this baseline corresponds to the candidate version in the Helm chart... which makes for a really really confusing user experience.

**Describe the feature/solution you'd like**
Create `v2alpha3` Iter8 experiment CRD, which will have the following schema for `versionInfo`.
```yaml
versionInfo: [a list of version detail objects ] # min length = 1
```

```yaml
# version detail
  weightObjRef: <current weight object ref>
  variables: <current name/value pairs>
```

**Differences from `v2alpha2`:
1. The words `baseline` and `candidates` have been dropped from versionInfo and the structure is now flattened to a single list.
2. The `name` field is dropped from version detail for the CRD. The Go type will continue to have a name field which will be auto populated by etc3 (and other Iter8 components) with the following convention: `version-0`, `version-1`, and so on (based on the index of the version in the versionInfo list).
3. The role played by the baseline in `v2alpha2` will be played by the first version in the versionInfo list.
4. The role played by candidates in `v2alpha2` will now be played by the tail (2nd, 3rd, ... last versions) in the versionInfo list.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
1. Makes the experiment CRD less confusing in conformance experiments used to test and promote candidate versions
2. Makes the experiment CRD simpler (flatter structure with fewer fields that need to be set by the user)

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes. The user-facing part of the design is described above. There is a level-2 design discussion which is required, since changing the CRD affects every component of Iter8.

**How will this feature be tested?**
- [ ] Existing tests will be modified so that they pass.

**How will this feature be documented?**
- [ ] Iter8.tools documentation will describe `v2alpha3` as well as `v2alpha2` experiment CRDs to start with (the latter will be deprecated and support for it will be removed eventually).

**Comment by kalantar** [comment]
Agree completely with remove baseline and candidates from versionInfo. It has impact in many places but all easy to find/modify. I think.  Less sure about removal of name. No problem is principle but need to review carefully to find where we might have used it or made an assumption about it.

**Comment by sriumcp** [comment]
I want to propose an additional simplification to `versionInfo`. 
***
Drop the `variables` section from `experiment.spec.versionInfo.versionDetail` objects.

1. The need for version specific variables in experiment spec, from the metrics perspective, will no longer exist in v2alpha3 due to #933 
2. The need for version specific variables in experiment spec, from a task perspective, will be greatly minimized in v2alpha3 due to #932 
3. Interpolation is still useful, especially using the `.this` construct, and especially in notification tasks. However, interpolation with version specific variables is really complicated to explain, let alone use.
4. Interpolation with version specific variables can still be enabled, if it is really needed, by introducing version specific variables as part of the task inputs. This will at least make sure that the template in the task (example, a templated script) is co-located with the version-specific variables instead of being spread out (partly in task, and partly in spec.versionInfo.versionDetail).

**Comment by sriumcp** [comment]
**Before:**

```yaml
apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: quickstart-exp
spec:
  target: default/sample-app
  strategy:
    testingPattern: Canary
    deploymentPattern: Progressive
    actions:
      loop:
      - task: metrics/collect
        with:
          versions: 
          - name: sample-app-v1
            url: http://current-sample-app.default.svc.cluster.local
          - name: sample-app-v2
            url: http://candidate-sample-app.default.svc.cluster.local
      finish: # run the following sequence of tasks at the end of the experiment
      - task: common/exec # promote the winning version      
        with:
          cmd: /bin/sh
          args:
          - "-c"
          - |
            kubectl apply -f https://raw.githubusercontent.com/iter8-tools/iter8/master/samples/knative/quickstart/{{ .promote }}.yaml
  criteria:
    requestCount: iter8-system/request-count
    objectives: 
    - metric: iter8-system/mean-latency
      upperLimit: 50
    - metric: iter8-system/latency-95th-percentile
      upperLimit: 100
    - metric: iter8-system/error-rate
      upperLimit: "0.01"
  duration:
    maxLoops: 10
    intervalSeconds: 1
    iterationsPerLoop: 1
  versionInfo:
    # information about app versions used in this experiment
    baseline:
      name: sample-app-v1
      weightObjRef:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: sample-app
        namespace: default
        fieldPath: .spec.traffic[0].percent
      variables:
      - name: promote
        value: baseline
    candidates:
    - name: sample-app-v2
      weightObjRef:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: sample-app
        namespace: default
        fieldPath: .spec.traffic[1].percent
      variables:
      - name: promote
        value: candidate
```

**Comment by sriumcp** [comment]
**After:**

```yaml
apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: quickstart-exp
spec:
  target: default/sample-app
  strategy:
    testingPattern: Canary
    deploymentPattern: Progressive
    actions:
      loop:
      - task: metrics/collect
        with:
          versions: 
          - name: sample-app-v1
            url: http://current-sample-app.default.svc.cluster.local
          - name: sample-app-v2
            url: http://candidate-sample-app.default.svc.cluster.local
      finish: # run the following sequence of tasks at the end of the experiment
      - task: common/bash # promote the winning version
        with:
          condition: CandidateWon
          script: "kubectl apply -f https://raw.githubusercontent.com/iter8-tools/iter8/master/samples/knative/quickstart/candidate.yaml"
      - task: common/bash # promote the winning version
        with:
          condition: not CandidateWon
          script: "kubectl apply -f https://raw.githubusercontent.com/iter8-tools/iter8/master/samples/knative/quickstart/baseline.yaml"
  criteria:
    requestCount: iter8-system/request-count
    objectives: 
    - metric: iter8-system/mean-latency
      upperLimit: 50
    - metric: iter8-system/latency-95th-percentile
      upperLimit: 100
    - metric: iter8-system/error-rate
      upperLimit: "0.01"
  duration:
    maxLoops: 10
    intervalSeconds: 1
    iterationsPerLoop: 1
  versionInfo:
    # information about app versions used in this experiment
    baseline:
      name: sample-app-v1
      weightObjRef:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: sample-app
        namespace: default
        fieldPath: .spec.traffic[0].percent
      variables:
      - name: promote
        value: baseline
    candidates:
    - name: sample-app-v2
      weightObjRef:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: sample-app
        namespace: default
        fieldPath: .spec.traffic[1].percent
      variables:
      - name: promote
        value: candidate
```
