### ISSUE TITLE
CandidateWatch CRD for auto deploying Iter8 experiments

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#864]
**Is your feature request related to a **problem**? Please describe the **problem**.**
When a new candidate is deployed during Iter8 experiments, the user's CD pipeline also needs to deploy an experiment object. This is simple in Helmex, but complex in non-Helmex experiments. This proposal is intended to simplify non-Helmex experiments.

**Describe the feature/solution you'd like**
A new CRD along the following lines.... the controller for this CRD will watch for the specified resource, and if changes are detected in the specified fields, will release a Helm chart. The Helm release will include an experiment, and can include additional resources.

Note that Iter8 experiment will do the usual things, like traffic shifting, an upgrade of the baseline version, gitopsy upgrade of the baseline version and so on... 

**Initial example**
```yaml
- kind: CandidateWatch
  metadata: <standard stuff>
  spec:
    # watch for the resource specified in resourceRef.. and after detecting changes ...
    # Helm install if this resource is created
    # uninstall when it is deleted
    # upgrade when one of the fields in the filter has changed.
    # Helm chart details are further below
    resourceUnderWatch:
      name: 
      namespace:
      kind:
      filter: [a list of field paths]
    values: helm values... can be static, or based on JSON paths (i.e., fields dynamically extracted from the referenced resource)
    repo: # helm repo
    chart: # helm chart
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Simplify CD pipelines involving Iter8 experiments. No need to set up experiments each time a new candidate arrives. Handled automatically by this controller instead.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes. TBD.

**How will this feature be tested?**
- [ ] Unit, Env and e2e-tests

**How will this feature be documented?**
- [ ] iter8.tools documentation.

**Comment by huang195** [comment]
1. I wonder if instead of creating yet another CRD, if we could encode this information as annotations to Iter8-supported resources, i.e., Deployments, Statefulsets, etc. 
2. This seems to be again Helm dependent looking at `repo` and `chart` fields. I wonder if option 1 is possible, whether or not Helm already leaves enough crumbs in the resource spec, so these are available implicitly.

**Comment by sriumcp** [comment]
@huang195 Just so I understood... 

1. No new CRD
2. Take an existing resource -- annotate it with appropriate annotations and may be add a bunch of labels also if it makes sense. Annotations could include helm repo and chart information (and dynamically constructed values are derived from the resource -- how is TBD).
3. Iter8 operator will watch for resources (perhaps filter them based on annotations/labels, for further processing -- i.e., Helm based instantiation of experiments and supporting resources).

Is this correct?

I think this is a fantastic idea, because it makes user's migration to Iter8 really really simple. Just add a few annotations/labels to resources that they're currently deploying -- and that's it.

**Comment by sriumcp** [comment]
In principle, Helm repo/chart info can be replaced with kustomize folder info, or jsonnet info... 

Helm is certainly the most popular of these templating choices though, and probably where we would want to start.

**Comment by kalantar** [comment]
Can a controller watch arbitrary resources for annotations? Or does it need to also have a notion of resource group/kind? I thought it still did.

I would like to see what the "values" field might look like. I would hesitate before adding a lot of annotations. But I do like that approach.

**Comment by huang195** [comment]
@sriumcp there's still some ambiguity in how the CRD/annotation is being used. Can you briefly describe a scenario, i.e., what resources are deployed in the initial state, what happens when a new image is available (what user has to do, what iter8 do under the cover), what needs to be cleaned up at the end, etc.

**Comment by sriumcp** [comment]
Yes, will make an attempt at fleshing out the details -- may be for 2 or 3 scenarios from our existing tutorials -- to see how this could play out (both for values, annotations, and also the mechanics of how experiment / promotion would occur).

**Comment by sriumcp** [comment]
Say the user wants to trigger an Iter8 experiment by dark launching a new version of an application ... here's a concrete example of the candidate watch functionality.
***
1. User already has a stable service and deployment, lets call them `hello` service and `hello` deployment.
2. `hello-candidate` comes along. User deploys `hello-candidate` which looks as follows.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-candidate
  annotations:
    # required for auto-triggering an experiment
    # same as the experiment target
    iter8.tools/simplex.target: <string that uniquely identifies the application under experimentation>
    # required for auto-triggering an experiment
    iter8.tools/simplex.repo: <Helm repo URL>
    # required for auto-triggering an experiment
    iter8.tools/simplex.chart: <Name of the Helm chart>
    # optional; not required for auto-triggering an experiment
    # values1.yaml; this optional file is intended to be defined once per application. 
    # This is not intended to change with each new candidate
    iter8.tools/simplex.values: <https://url.to.values.yaml> 
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
3. Iter8 watch controller is pre-configured to watch for changes to deployments (lets say in a specific namespace; it can even be specific named deployments, example `hello-candidate`). Details to be worked out here but K8s clientsets have ways to filter watch today.
4. Iter8 watch controller constructs a `values2.yaml` file by simply copying over the deployment spec and metadata (including labels, and annotations) into a file called `values2.yaml` (it doesn't matter of most of these fields are un-used by the chart; they are simply noise and can be ignored safely and will have no role to play as far as Helm chart is concerned).
5. Iter8 watch controller merges `values2.yaml` and `values1.yaml` into `values3.yaml`. Note that `values2.yaml` can contain any `dynamic` data associated with the new candidate (example in the form of labels/annotations/other fields like container images, etc.). `values1.yaml` is intended to be static information about the application defined once at the beginning of time.
6. Iter8 watch controller deploys the Helm chart specified in the annotation. The chart will contain the Iter8 experiment template, as well as any supporting resources that are transient and needed for this experiment (for example, `hello-candidate` k8s service in this example).
7. At this point, the experiment can do its usual stuff, including traffic shifting, A/B testing based on a metric (perhaps defined as part of the Helm chart), and so on.
8. At the end of the experiment, Iter8 can do version promotion (either through Git by updating a repo, or in-cluster).

**Comment by sriumcp** [comment]
Key advantages of the above design ... 
***
1. Create standardized Helm charts that be can used within simplex annotations such as the above. If your use-case fits within one of these standardized ones, you don't need to understand anything about Iter8 experiment CRD. All you need to know is how to configure `values1.yaml` (which has to do with your application/CI/CD environment; not Iter8).
2. If your use-case cannot be covered by existing templates, no problem -- simply choose the nearest template, and modify it  as needed for your use-case.
3. There is no assumption that the user is using Helm for the application. There is a Helm dependency, but it is only at the Iter8 watch controller level, not for the end-user. The end-user may or may not use Helm to release the target resource being watched (it doesn't matter for watch controller purposes; of course, the Helm chart itself needs to pay attention to these details since it is creating the experiment).
4.  You can migrate an existing application to Iter8-based release very easily. Simply start annotating your candidate resource and you are good to go!
5. GitOps can be as simple as creating a new resource (example `deployment` manifest) in Git every time a new candidate comes along (and that's it).

**Comment by sriumcp** [comment]
@huang195 @kalantar @fabolive Please keep comments coming here... meanwhile, I can try prototyping an initial version of this.

**Comment by huang195** [comment]
Looks good to me. One thing to think about is if we can add annotations to the baseline version instead of candidate version. It's more complicated as replicaset controller would interfere with our intention, but it does reduce user's involvement and gives it more of a k8s-native feeling. Maybe something like

```
kubectl annotate deployment app targetImage=app:v2
```

would trigger the operator to provision the candidate deployment on behalf of the user. It's slightly different from

```
kubectl set  image deploy/app app=app:v2
```

but it's close, and can work in both gitops and non-gitops setting. Alternatively, the `kubectl annotate` command could point to a Helm chart (as you have in the example), so Iterr8 can deploy the candidate deployment along with other resources. Net net is can we reduce user effort when rolling out new versions?

**Comment by sriumcp** [comment]
@huang195 The building blocks described so far (controller which watches a target resource and helm deploys) can be used in several different ways, so yes, we can use it to annotate baseline or annotate candidate.

In fact, in domains like Knative, this distinction is totally blurred (the same service is used to create both).

So, absolutely yes, the suggestion you made above is very much on the table -- and we can decide on the best way to approach individual use-cases using this building block.

**Comment by sriumcp** [comment]
When editing baseline version, no setting image... or spec... only annotations.

**Comment by kalantar** [comment]
I really not following the logic here. 

1. is the values file referenced by the annotation one of `values1.yaml` or `values2.yaml`?
2. should we consider values file defined in a configmap? Perhaps this is easier than making available remotely?
3. Are we assuming that a user creates a candidate Deployment object? While this should be an option, I thought we were trying to imagine a scenario in which the user merely annotated or modified the Deployment for the stable version.
4. the benefits include that the user need not use helm for application, but it seems like it is necessary if the watch crd is creating the candidate objects from the helm file. agree that this may not apply to the promotion step but then seems like double work

**Comment by sriumcp** [comment]
@kalantar

1. `values1.yaml` is referenced in the annotation. `values2.yaml` is generated automatically (it is simply the resource being watched minus its status section).

2. +1 for ConfigMap; Git URL might not be that hard (because, the ConfigMap probably is coming from Git repo anyway; or generated by a Helm chart in a Git repo perhaps ... ). 

3. Both baseline  and candidate annotations can be supported through this method. I feel there will be both types of use-cases / usage scenarios. Baseline deployment annotations (while good for basic use-cases), will not be the sufficient for many (if not most) users. What if I want to introduce new fields (like environment variables), or a sidecar, or modify the deployment object in other non-trivial ways in my next release? Describing them all as annotations is going to be painful ... and describing the logic for creating the candidate, using those baseline annotations is going to be even more painful. Instead, simply create the candidate deployment and annotate away!

Good news: both options are made possible by this building block.

4. I agree with your comment on 4 above... definitely some thought is required here to avoid the double work. Here's a possibility -- if baseline is annotated, the logic for creating the candidate is part of the experiment (not helm chart). For example, simply copy the baseline, remove some of iter8 simplex annotations, and add the suffix `-candidate` to the name and deploy. If candidate is annotated, there is no need to create a candidate deployment in the experiment.

**Comment by kalantar** [comment]
> Both baseline and candidate annotations can be supported through this method. I feel there will be both types of use-cases / usage scenarios.

Agreed. But I think we are beginning to look at this from the Iter8 perspective and not the user perspective.  Iter8 seems to be demanding a new deployment because something more than image has changed. 

A user might use either approach: 

Single Deployment Model -- only ever have a single deployment. When make changes -- any changes modify the existing deployment (can do for env var or add a sidecar kinds of changes too).

Two Deployment Model -- create a new deployment (and maybe new service) and have both then change routing in some way.

Annotations are added to hint to Iter8 that it needs to create an experiment. Can it do so without forcing the user to do something else. The use of annotations to capture this limited and perhaps acceptable only when the image changes. But forcing a new deployment model also does not seem right. 

In fact, even in the single deployment model, there is a second deployment model -- the manifest the user is "applying" is a second model (reusing the name). Is there a point at which the controller sees both the existing model and the new model? In this case, it could perhaps determine what to do?

**Comment by sriumcp** [comment]
I am not able to follow the discussion re: single vs two deployment models... but there are a few concerns this is bringing up which I do follow and list here.. 

1. What should the user do in order to `initiate` a new release? The simpler this is the better (as it makes CI/CD/GitOps) easier. Current options are, 1) annotate baseline deployment, and 2) create candidate deployment, and annotate candidate deployment.
2. What will the Helm chart deploy? I don't think this should be anything other than  the Iter8 experiment & metrics. Managing half the application resources non-Helm way and the other half through Helm (and that too not directly, but opaquely by the Iter8 controller is a bad idea).
3. What will the Iter8 experiment deploy? There are options here... the experiment can create transient resources, like a candidate deployment and service, and re-use an existing route (or an ingress or virtual service resource for traffic shifting, if needed).
4. How will the Iter8 experiment shift traffic (directly in cluster? through Git repo? through notifications? what if the application is deployed using Helm?)
5. How will the Iter8 experiment promote the new version? (directly in cluster repo? through Git? through notifications? using a helm command?)

***

What would the user to if they were to experiment without Iter8? Specifically how would they do 3, 4 and 5? Iter8 should enable the same experience for seamless integration. Since different users will go about 3, 4 and 5 in different ways, Iter8 should enable different options in the experiment for 3, 4, and 5. For example ... 

***

User creates a candidate deployment, a candidate service, and a virtual service to experiment with, and deletes them at the end of their experiment. They do this through GitHub declaratively. At the end of the experiment, these transient resources are wiped out from GitHub. The Iter8 experiment should do be able to do the same thing ... 

*** 

User uses Helm values to change the state of the application through GitHub. Iter8 should enable the same thing (see [this example](https://iter8.tools/0.7/tutorials/knative/slovalidation-helmex-gitops/) that illustrates how Iter8 can achieve this today).

**Comment by huang195** [comment]
@sriumcp Hopefully I didn't miss anything in this long thread, but ignore if I misunderstood something. I'm using the example you gave above:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-candidate
  annotations:
    # required for auto-triggering an experiment
    # same as the experiment target
    iter8.tools/simplex.target: <string that uniquely identifies the application under experimentation>
    # required for auto-triggering an experiment
    iter8.tools/simplex.repo: <Helm repo URL>
    # required for auto-triggering an experiment
    iter8.tools/simplex.chart: <Name of the Helm chart>
    # optional; not required for auto-triggering an experiment
    # values1.yaml; this optional file is intended to be defined once per application. 
    # This is not intended to change with each new candidate
    iter8.tools/simplex.values: <https://url.to.values.yaml> 
```

My suggestion is to not use Helm-specific fields here as those bound Iter8 to Helm, and we don't want to create hard dependencies unless there's no other way around. I'm wondering if we could use a generic webhook and pass it a list of parameters. An example is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-candidate
  annotations:
    iter8.tools/webhook: http://<github workflow we want to invoke>
    iter8.tools/github-token: <github token>
    iter8.tools/parameters: {'chart': <location of the chart>, 'parameters': <helm parameters>}
```

So the idea is that we implement different backend services (github actions, tekton pipelines, etc.) that can be invoked by webhook calls. It is the responsibility of the backend service to do what needs to be done, i.e., deploy an helm chart in the cluster, or run a script that does a bunch of things. This would allow us (and users) to implement other mechanisms other than Helm in the near future.
