### ISSUE TITLE
notification/github-workflow task

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#870]
**Is your feature request related to a **problem**? Please describe the **problem**.**
The notification/http task enables calling github workflows as part of an action. However, it is wordy to express and easy to make mistakes. A derivative task, notification/github-workflow, can be used to easily express the needed parameters and convert to an http task.

Proposed definiton:

```yaml
repository:  org/repo # required
ref:  branch # optional, default master
workflow:  workflow.yaml # required, name of file defining workflow
secret: ns/mytokensecret # name of secret form namespace/name; required; must contain token
inputs: # workflow inputs
- name: arg
  value: val
ignoreFailure: true # determines if task failire causes experiment failure; optional; default true
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Reduce likelihood of errors expressing a request to execute a github workflow.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Use this thread.

**How will this feature be tested?**
- [x] test cases

**How will this feature be documented?**
- [ ] task refference document
