### ISSUE TITLE
Convert `metrics/collect` task into a `load-test-with-fortio` task with support for `POST` APIs

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#940]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Fortio has numerous options for testing both `GET` and `POST` APIs. Currently, they are not available as part of `metrics/collect` task. In particular, testing `POST` APIs is not possible today with builtin metrics.

**Describe the feature/solution you'd like**
1. Rename `versions` to `versionInfo` in `metrics/collect` task.
2. Rename `metrics/collect` to `load-test-with-fortio`
3. Use Iter8 defined constants `{{ PayloadFile }}` and `{{ FortioOutputFile }}`
4. Support resolution of destinations with timeouts. Sometimes, this is checking readiness of routes (as opposed to readiness of kubernetes resources; they are different).
5. Enable the use of **any** fortio load testing command. For example:
```yaml
- task: load-testing-with-fortio
  with:
    resolve:
      destinations: ["hello.default", "hello-candidate.default"] # do not start if you cannot resolve these paths
      timeoutSeconds: 20
    versionInfo:
    - script: | # test a POST API. A fortio file named `output.json` is expected as a side-effect of the script
        curl https://payload.com -o {{ PayloadFile }}
        fortio load -json {{ FortioOutputFile }} -grpc -ping -grpc-ping-delay 0.25s -payload-file {{ PayloadFile }} -c 2 -s 4 hello.default
    - script: | # re-use payload.json from earlier script
        fortio load -json  {{ FortioOutputFile }} -grpc -ping -grpc-ping-delay 0.25s -payload-file {{ PayloadFile }} -c 2 -s 4 hello.default
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Better load testing, including ability to test POST APIs.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Leverage Fortio documentation. Leverage Fortio features for testing POST APIs.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes. See above.

**How will this feature be tested?**
- [ ] Existing tests should pass.

**How will this feature be documented?**
- [ ] Change to `metrics/collect` task documentation.
