### ISSUE TITLE
Drop `versionInfo` section from experiment

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#941]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Specifying traffic shift parameters (like weightObjRefs for versions) is great if traffic shifting is happening in the same cluster where etc3 is running. But this is problematic in several other use-cases for the following reasons... 
1. Traffic shifting may need to be gitops-y rather than imperative / in-cluster
2. Traffic shifting may need to be affected through Helm for Helm users, for example, `helm upgrade ... --set v1.weight=20 --set v2.weight=80` is more reasonable for a Helm application than directly changing an in-cluster resource
3. etc3  and the resources being manipulated may be in different clusters (an example of such a scenario is [here](https://www.ibm.com/cloud/blog/announcements/validating-your-code-engine-application-with-iter8))

**Describe the feature/solution you'd like**
1. Drop `versionInfo` section from experiment  spec. Already #862 drops variables out of version info. This drops version info itself. Replace the `versionInfo` section by a simple `numVersions` integer (which needs to be `min` 1).
2. Drop `deploymentPattern` field from `spec.strategy`. Note that `testingPattern` is already being dropped as discussed #862.
3. Move etc3 iteration logic into well defined tasks. Specifically, write three tasks as follows, which are meant to be embedded within a loop action of an experiment:
```yaml
# this task will update the current weight distribution in experiment status
# by getting the actual weights from cluster
- task: clusterops/get-weights
  with:
    versionInfo: <list of weight Obj refs -- just like we would normally provide>
```

```yaml
# this task will talk to analytics and update the weights section of status.analysis
# etc3 still has the concept of Iterations and talks to the analytics service as usual
# this double work can be optimized later, if there is a real need for it
# for now, this double work ensures everything works smoothly even if there are no loop actions
- task: common/get-weight-recommendations
  with:
    shiftWeight: true # by default, this is false, so no weight shifting occurs; only analysis
    maxCandidateWeight:
    maxCandidateWeightIncrement:
```

```yaml
# this task requires clusterops/get-weighs to be specified earlier in the action pipeline, 
# it will reuse versionInfo from there.
- task: clusterops/set-weights # re-uses params from clusterops/get-weights
```

**Crucially, we can change clusterops to gitops, or helmops or whatever by writing other tasks.**

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
1. Enable GitOps-y weight shifting.
2. Enable HelmOps-y weight shifting.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Eventually, this will pave the way for integrating other arbitrary analytics services with their own API response formats. The task mechanism can be used to reformat / transform the response from these external analytics services.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes, see above for an initial design.

**How will this feature be tested?**
- [ ] Unit, env, and e2e tested.

**How will this feature be documented?**
- [ ] Tasks documentation in Iter8.tools

**Additional context**
Locating versionInfo for weight shifting with appropriate tasks avoids [spooky action at a distance anti-pattern.](https://en.wikipedia.org/wiki/Action_at_a_distance_(computer_programming))

**Comment by sriumcp** [comment]
**Note:** This also means we can drop `experiment.spec.strategy` and replace it by `experiment.spec.actions` instead.

**Comment by sriumcp** [comment]
Please see https://github.com/iter8-tools/iter8/discussions/942#discussion-3505626 for an example where `numVersions` is used.

**Comment by kalantar** [comment]
I like an approach that puts the implementation of traffic shifting in the same place of the experiment. It is nicer than its implicit (from the values of these three fields) but if you want to do it set the fields like that and use tasks. ...). So yes to that.

In this context, we should perhaps jot down the interfaces for the three tasks, helm, gitops and clusterops  with the idea that we want them to look as similar as possible for the common things.

**Comment by kalantar** [comment]
I'm a little less happy with the get-weights methods. It is a nice feature that Iter8 is reporting the current weights whenever it can; it doesn't require the explicit request of the user which this approach does. It's probably worth the tradeoff.

**Comment by kalantar** [comment]
If we remove all these things, the only thing left in strategy is actions. and number of versions. We should get rid of strategy and move actions to top level. Is there renaming there that needs to take place?

**Comment by kalantar** [comment]
I feel like get-weights and set-weights (and maybe other stuff) have common versionInfo details. Do we need to repeat them? Should we consider a notion of versionInfo defined at the top level which can be augmented or even overridden by the individual tasks? Something like:
```yaml
actions:
  versionInfo:
    - weightObjectRef:
       variables:
    - weightObjectRef:
      variables:
  loop:
  - task: clusterops/set-weights
  - task: clusterops/get-weights
 finish:
 - task: common/bash
  with:
     versionInfo:
     - variables:
     - variables:
     script: 
```

**Comment by kalantar** [comment]
I don't like a numVersions field. Is it fair to assume that a list of versions must be present somewhere. Some task or some metric? Can we just find it implicitly?

**Comment by sriumcp** [comment]
When using templates, the idea behind `versionInfo` is that template would be co-located with the data for the template (versionInfo). Separating them makes the experiment hard to read and harder to author.
***
weight shifting requires its own version info inputs;
metrics requires its own version info inputs, different from above inputs;
promotion requires its own version info inputs; different from above inputs;
***
Bunching these inputs together means the user will need to go back and forth between a task and the version info section, which is really not desirable.
***
versionInfo input to a task is really no different from any other input.
we wouldn't bunch up all the task inputs together in the action section.
we shouldn't do this with versionInfo either.
***
I don't understand the problem with `numVersions`. I don't think there can be a field in the entire experiment spec that is simpler to explain that this :-) 

This field is the source of truth about `numVersions`. Every other versionInfo (in metrics / tasks) will be validated against numVersions.

**Comment by sriumcp** [comment]
> I'm a little less happy with the get-weights methods. It is a nice feature that Iter8 is reporting the current weights whenever it can; it doesn't require the explicit request of the user which this approach does. It's probably worth the tradeoff.

We don't need to separate get and set. We can simply do... 

```
- task: manipulate-incluster-weights
  with:
    get-and-set: true # by default this is false; i.e., only get is performed
```

No repetition.
***
Another way (described above) is that, no need to provide any inputs for set (it can assume that there is a corresponding get task defined earlier, and get the inputs from the get task instead).

**Comment by sriumcp** [comment]
>  It is a nice feature that Iter8 is reporting the current weights whenever it can; it doesn't require the explicit request of the user which this approach does. It's probably worth the tradeoff.
***
For GitOps users, the source of truth is going to be Git repo.

For Helm users, the source of truth is going to  Helm values.
***
I think it is better if we don't say, for cluster ops, things will work one way (because it is implemented in our controller, and we don't want to move it to the task), and for helmops and gitops do it a different way.

**Comment by sriumcp** [comment]
The current experiment spec (specifically, its versionInfo section) was created before the concept of handler tasks as it exists today was conceived. It is a good time to revisit the experiment spec which is starting to show its limitations, and the above is one such attempt.

**Comment by kalantar** [comment]
> > It is a nice feature that Iter8 is reporting the current weights whenever it can; it doesn't require the explicit request of the user which this approach does. It's probably worth the tradeoff.
> 
> For GitOps users, the source of truth is going to be Git repo.
> 
> For Helm users, the source of truth is going to Helm values.

Is the current weights not a needed/desired input to analytics? It doesn't matter if helm or git are the source of truth. We need an input for analytics. I guess this is not an absolute since the weightObjRef are optional. We cannot just assume there is another method with the needed input

**Comment by kalantar** [comment]
> Bunching these inputs together means the user will need to go back and forth between a task and the version info section, which is really not desirable.

I wasn't suggesting that we bunch them all together all the time. I was suggesting that we consider a mechanism to allow us to define an input that is used in common for a number of tasks. Not all tasks. Not tasks and metrics and ... I was just observing that it will be equally annoying to duplicate variables.

**Comment by kalantar** [comment]
> I don't understand the problem with numVersions. I don't think there can be a field in the entire experiment spec that is simpler to explain that this :-)

I've been thinking more about this. I think we should reconsider eliminating version names (or labels). A tool like iter8ctl needs a label to assign to versions. It should be meaningful to the user. v-0, v-1 and v-2 aren't going to be unless the user also wrote the experiment and is intimately familiar with with it.  It may be reasonable to have a simple `versions` which allows definition of version labels. For example,

```yaml
versions: ["current", "candidate"]
```

**Comment by sriumcp** [comment]
> Is the current weights not a needed/desired input to analytics?

It is. But the input can be read from whatever is considered the source of truth about the app (helm values / git file), rather than the cluster (unless we are manipulating objects in cluster).

**Note:** fully fleshed out examples to follow soon.

**Comment by sriumcp** [comment]
> it will be equally annoying to duplicate variables.

Yes. Duplication of variables can be avoided by defaulting variables from earlier tasks. Example, if `set-weights` task is preceded by a `get-weights` task (reasonable; get current weights, and then find recommended weights, and then set it), `set-weights` can default shared inputs from the `get-weights` task.

Some examples for inputs that can be shared in this way: helm values from git, helm values from helm-release secret in cluster, and a yaml file with weights in the git repo (weight references are not always in-cluster weightObjRefs).

**Note:** fully fleshed out examples to follow soon.

**Comment by sriumcp** [comment]
## Concepts
1. `WeightsFilePath` is an Iter8 template constant. It should point to a YAML file (not necessarily a k8s manifest).
2. Token is an Iter8 template variable. If a proper secret with a token is supplied, it would have the value of the token.
3. Task `get-and-set-file-weights` does the following.
    * update `currentWeightDistribution` in the experiment based on weights in the file pointed to by `WeightsFilePath`
    * talk to the analytics service to get the recommended weights
    * update file pointed to by `WeightsFilePath` based on the recommended weights

## Helm example
```yaml
action:
  loop:
  - task: common/bash
    with: 
      script: helm get values my-app > {{ WeightsFilePath }}
  - task: get-and-set-file-weights
    with:
      versionInfo:
      - <yq path to 1st version weight>
      - <yq path to 2nd version weight>
  - task: common/bash
    with:
      script: helm upgrade --install -f {{ WeightsFilePath }}
```

## GitOps example

```yaml
action:
  loop:
  - task: common/bash
    with:
      secretName: <name of the secret with token>
      script: |
        git clone https://sriumcp:{{ Token }}@github.com/gitops/project
        cp project/<relative path to weights file> {{ WeightsFilePath }}
  - task: get-and-set-file-weights
    with:
      versionInfo:
      - <yq path to 1st version weight>
      - <yq path to 2nd version weight>
  - task: common/bash
    with:
      script: | 
        git commit -a -m "updated weights"
        git push origin main -f
```

## ClusterOps example

```yaml
action:
  loop:
  - task: common/bash
    with:
      script: "kubectl get vs -n bookinfo -o yaml > {{ WeightsFilePath }}"
  - task: get-and-set-file-weights
    with:
      versionInfo:
      - <yq path to 1st version weight>
      - <yq path to 2nd version weight>
  - task: common/bash
    with:
      script: "kubectl apply -f {{ WeightsFilePath }}
```

**Comment by sriumcp** [comment]
```yaml
action:
  loop: # getting and setting weights from git repo
  - task: git-clone
    with: # this task will update `currentWeightDistribution` in the experiment status
      release: <name of the helm release>
      versionInfo: # length of this list needs to match length of the versionInfo list in the experiment
      - <jq expression to extract the 1st version weight>
      - <jq expression to extract the 2nd version weight>
    # this task will talk to analytics and get weight recommendations and update the experiment status
    # note that the controller wouldn't need to talk to analytics, when this task is implemented
    - task: get-weight-recommendations 
      with: # optional
        max-candidate-weight: <as in spec.strategy.weights today>
        max-candidate-weight-increment: <as in spec.strategy.weights today>
    - task: common/bash
      with: # this task uses weights recommended by analytics, i.e., weights in the experiment status at this point
        script: helm upgrade --install \
                --set stable.weight={{ RecommendedWeightFor 'stable' }}  \
                --set candidate.weight={{ RecommendedWeightFor 'candidate' }}
```
