### ISSUE TITLE
Get rid of version recommended for promotion and replace it with less arcane template functions

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#945]
**Is your feature request related to a **problem**? Please describe the **problem**.**
In the `common/exec` task, without any versionRecommendedForPromotion (an optional field in experiment status), the task will fail; in the `common/bash` task, without any versionRecommendedForPromotion, the shell script will interpolate to garbage string and try to execute, probably resulting in failure or some other undesirable behavior which is opaque and hard to debug. In notification tasks, interpolation will result in weird notification messages.

`versionRecommendedForPromotion` field leads to [spooky action at a distance anti-pattern.](https://en.wikipedia.org/wiki/Action_at_a_distance_(computer_programming))

**Describe the feature/solution you'd like**
Support fail safe interpolation using version-specific variables like the following. This has the advantage of getting rid of versionRecommendedForPromotion (one less concept), provide more direct and easier to understand templates, and making the interpolation fail safe at the same time. 

```yaml
- name: common/shell
  condition: WinnerFound()
  with:
    # changes scope of template evaluation from experiment struct to exp.Winner() map
    script: kubectl apply -f {{ .Winner | .manifest }}
    versionInfo:
    - variables: # for baseline
      - name: manifest
        value: https://baseline.manifest.yaml
    - variables: # for candidate
      - name: manifest
        value: https://candidate.manifest.yaml
```

```yaml
- name: common/shell
  with:
    # changes scope of template evaluation from experiment struct to exp.WinnerOrBaseline() map
    script: kubectl apply -f {{ .WinnerOrBaseline | .manifest }}
    versionInfo:
    - variables: # for baseline
      - name: manifest
        value: https://baseline.manifest.yaml
    - variables: # for candidate
      - name: manifest
        value: https://candidate.manifest.yaml
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Easier to understand interpolation with version specific variables. More robust interpolation with version-specific variables.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Please see above. Easy to implement using [go template functions](https://pkg.go.dev/text/template#hdr-Arguments) as described below. 

**How will this feature be tested?**
- [ ] Unit tested. E2e tested in tutorials.

**How will this feature be documented?**
- [ ] iter8.tools documentation.

**Additional context**
Related discussion in this pr #https://github.com/iter8-tools/iter8/pull/944

The implementation can be simple -- 
1. `func (exp *Experiment) Winner() (map[string]interface{}, error)` would return the map of variables corresponding to winner if there is one, or error. For now, the map can be with versionInfo in the task, which if present, overrides, the versionInfo in the experiment spec. In `v2beta1` since the latter will be dropped, it would be dropped here too... 
2. `func (exp *Experiment) WinnerOrBaseline() map[string]interface{}` would return the map of variables corresponding to winner if there is one, or would return the map for the baseline (which always is present). For now, the map can be with versionInfo in the task, which if present, overrides, the versionInfo in the experiment spec. In `v2beta1` since the latter will be dropped, it would be dropped here too... 

I don't believe anything else is needed for this to work.
***
Result: the following will become a valid template ... that can be executed with experiment struct.
```go
{{ .Status.Analysis != nil }} is one and {{ .Winner | .manifest }} is another and {{ .WinnerOrBaseline | .manifest}} is yet another
```
