### ISSUE TITLE
Get rid of `versionInfo` based templating. Get rid of `versionInfo` field from `tasks` and `experiment.spec`.

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#953]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Templating in experiment is complicated. Templating based on version specific information takes this complication to a higher level and makes it really complicated.

**Describe the feature/solution you'd like**
Drop `versionInfo` based templating. Drop `versionInfo` field from all tasks and experiment spec. Version info is still required for metrics as described in #942; this is ok since we are not planning to use it for version specific templating within metrics.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Makes experiments less voodoo and more easy to read/write.

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
* Makes tutorials less voodoo and more easy to read/write.
* Makes task development less complicated. Templates will not have version-specific variables. They can still interpolate based on experiment-level variables / functions.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes, see above. The main disadvantage of this approach is that it can make `common/bash` tasks and individual metrics longer and repetitive. For `common/bash`, this may not be such a big disadvantage if it is short to begin with. Enhancements like #954 should make things even more compact. For metrics, we are giving up brevity for the sake of explicitness / ease of understanding. Metrics is one of the harder things for users to get right to begin with; ease of understanding is more important to have here compared to brevity.

As discussed in #941, `experiment.spec` will now have a `versionNames` field which is simply a list of version names (strings).

**How will this feature be tested?**
- [ ] Existing tests need to work (and may need to be restructured)

**How will this feature be documented?**
- [ ] iter8.tools documentation to be updated.

**Comment by sriumcp** [comment]
Note: This issue is related to but different from #819

**Comment by sriumcp** [comment]
**Note:** Please see #942

**Comment by sriumcp** [comment]
# with condition
```yaml
- if: WinnerFound()
  run: kubectl apply -f https://baseline.com.yaml
- if: not WinnerFound()
  run: kubectl apply -f https://candidate.com.yaml
```

***

# with version info
```yaml
run: kubectl apply -f https://{{ WinnerOrFirst | manifest }}.com.yaml
versionInfo:
- manifest: baseline
- candidate: candidate
```

We will start with conditions. We will always have the option of introducing versionInfo as above, through non version-breaking CRD changes.
