### ISSUE TITLE
Drop privileged mode from iter8 install using docker

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8#959]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Iter8 installation steps for domains like CE uses a privileged Docker-in-docker mode. We want to remove the privileged docker dependency so as to run iter8 as a job in these domains

**Describe the feature/solution you'd like**
The solution will run iter8 analytics run locally. The handler will be able to update and read a local experiment file.

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Reduce the authorization required to run iter8 as a job/pod in some domains.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes. Please see this thread.

**How will this feature be tested?**
- [ ] Will be tested on CE and will replace the current tutorial on ibm cloud

**How will this feature be documented?**
- [ ] Will be documented on CE doc page

**Comment by sriumcp** [comment]
**End-goal**
Run a job as follows.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: handler
spec:
  template:
    spec:
      serviceAccountName: iter8-handlers
      containers:
      - name: iter8-handler
        # to change handler version, edit the line below
        image: iter8/handler:0.1.29
        command: ["bin/sh"]
        args: 
        - "-c"
        - |
          helm template <some chart> > /scratch/experiment.yaml
          handler run -a start -f /scratch/experiment.yaml
        env:
        - name: ACTION
          value: start
        - name: LOG_LEVEL
          value: trace
      - name: iter8-analytics
        image: iter8/analytics:0.1.29
        command: ["python"]
        args: 
        - |
          iter8-analytics.py
        env:
        - name: LOG_LEVEL
          value: trace
      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: 300
```

The `helm template` line would above would create `/scratch/experiment.yaml` which looks as follows.

```yaml
apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: slo-validation-mz8py
spec:
  # target identifies application for which SLO validation experiment is performed
  target: app
  strategy:
    # this experiment will perform a conformance test
    testingPattern: Conformance
    actions:
      start:
      - task: metrics/collect
        with:
          time: "5s"
          versions:
          - name: my-app
            url: "http://hello.myns.svc.cluster.local:8080"
            qps: 8
      - task: analytics/get-recommendation
        with:
          URL: http://localhost:9090
  criteria:
    requestCount: iter8-system/request-count
    indicators:
    - iter8-system/error-count
    objectives:
    - metric: iter8-system/mean-latency
      upperLimit: "50.0"
    - metric: iter8-system/error-rate
      upperLimit: "0.0"
    - metric: iter8-system/latency-95th-percentile
      upperLimit: "100.0"
  duration:
    intervalSeconds: 1
    iterationsPerLoop: 1
  versionInfo:
    # information about app versions used in this experiment
    baseline:
      name: my-app
```
