### ISSUE TITLE
Move iteration logic to tasks

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#970]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Today iter8 has built in logic to read and modify traffic weights. However, if another mechanism such as helm or gitops is used, the user must use loop tasks and modify the experiment to use loops.

**Describe the feature/solution you'd like**
Replace the iter8 logic with tasks that mirror those used for gitops and/or helm. The approach to read/set weights is then the same for all approaches.  This is related to elimination of `Spec.VersionInfo` (issue https://github.com/iter8-tools/iter8/issues/953).

Tasks to look something  like:

```yaml
# this task will update the current weight distribution in experiment status
# by getting the actual weights from cluster
- task: clusterops/get-weights
  with:
    versionInfo: <list of weight Obj refs -- just like we would normally provide>
```

```yaml
# this task requires clusterops/get-weighs to be specified earlier in the action pipeline, 
# it will reuse versionInfo from there.
- task: clusterops/set-weights # re-uses params from clusterops/get-weights
```

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Common approach to writing experiment for different assumptions.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Use this issue.

**How will this feature be tested?**
- [ ] Modify existing test cases; create new ones in handler

**How will this feature be documented?**
- [ ] Reference documentation updated; handler documentation updated.

**Additional Context**
This was originally documented as part of issue https://github.com/iter8-tools/iter8/issues/941 which is now closed.
